### ISSUE TITLE
Bowser didn't recognize snap installed  browsers like chromium snap

### ISSUE THREAD

**Issue by kerozoli** [blipk/bowser-gnome#1]
Thanks for this extension it's very useful however it couldn't handle one of my use case :
Bowser didn't recognize snap installed  browsers like chromium snap
( I mostly want to use it to fix chromium snap issue with xdg-open links like slack login)

**Comment by blipk** [comment]
Turns out they keep their .desktop files in another directory, have added it to the search path, you can update extension.js with the updated one from here and I will push a release soon enough.

Note: Snap doesn't install icons properly so currently no icons will be shown for snap apps in the mnu.
