### ISSUE TITLE
[Feature] Support for Firefox profiles

### ISSUE THREAD

**Issue by CiottiGiorgio** [blipk/bowser-gnome#14]
I would be great to have support for Firefox profiles as it's a great way to segregate personal/work web browsing.

It would be enough to just let the user manually add a definition for a browser (that in this case would just be `<firefox command> -p work-profile`). Ideally the extension could inspect the list of Firefox profiles and detect them as separate instances but it would kind of be overkill for something so uncommon.

I have made my own python script to solve this in the past but it would be great to have this solution integrated in a tool that already has a lot of machinery!

**Comment by blipk** [comment]
Hi @CiottiGiorgio 

I believe someone asked something similar in the past, and I will make the same suggestion.

The easiest way to achieve that would just be to duplicate your Firefox .desktop file and give it a new name as well as adding the launch flags to the params for whichever profile you want to associate with that desktop file.

You can find .desktop files in /usr/share/applications and ~/.local/share/applications

**Comment by CiottiGiorgio** [comment]
Worked like a charm! Thanks!

**Comment by blipk** [comment]
For reference in setting up the exec= in .desktop files for anyone else who needs to do this or similar:
https://peter.sh/experiments/chromium-command-line-switches/
https://wiki.mozilla.org/Firefox/CommandLineOptions
