### ISSUE TITLE
[Feeature] add support for gnome 42.4

### ISSUE THREAD

**Issue by dkocich** [blipk/bowser-gnome#15]
**Is your feature request related to a problem? Please describe.**
right now it says in gnome extensions that my gnome version is not supported.

**Describe the solution you'd like**
support LTS ubuntu and its gnome version

![image](https://user-images.githubusercontent.com/6165660/190490621-d8655b21-90ac-4c2e-81a2-0b3bf10fe899.png)
![image](https://user-images.githubusercontent.com/6165660/190490890-29907a3d-ddbb-45de-97f3-77db1aee8b79.png)

**Comment by blipk** [comment]
Hi @dkocich 
Everything should work, just havent had much interest on this.

Anyway I've bumped the version in `metadata.json` so it will run on 40-43 - have uploaded this to extensions.gnome.org too but takes a few days to be approved, so feel free to use the zip file in the repo until then.

If you run into any issues running this on 42, please open another issue.

**Comment by dkocich** [comment]
I just updated from gnome extensions and it works fine. Thank you.
