### ISSUE TITLE
[Feature] Add options to open links in incognito/private mode or ignore

### ISSUE THREAD

**Issue by joselsegura** [blipk/bowser-gnome#16]
It will be great if I can setup some rules for NSFW links to be ignored or opened in incognito/private mode

To ignoring links, Bowser should add an option at the bottom of the browsers offered when creating a new rule.
For the incognito/private mode, a good solution could be, after creating a new rule, the user can edit the rule and add a toggle to open in the configured browser, but in the incognito/private mode.

I didn't considered any alternative, it just came to my mind after fixing a minor problem with the configuration of Bowser.

**Comment by blipk** [comment]
See the pinned issue: https://github.com/blipk/bowser-gnome/issues/14

You need to set up .desktop files for your browsers with the correct CLI args to open in whatever mode you need.

See:
https://peter.sh/experiments/chromium-command-line-switches/
https://wiki.mozilla.org/Firefox/CommandLineOptions

**Comment by joselsegura** [comment]
Good point, I didn't think on that solution (and I have one desktop file for one of my Firefox profiles, so it's more or less the same!).

Thank you for pointing out
