### ISSUE TITLE
[Feeature] chrome/chromium progressive web app open links in firefox

### ISSUE THREAD

**Issue by alanmcg** [blipk/bowser-gnome#18]
I am using microsoft teams in a chromium PWA, unfortunately this is the only reliable way to use Teams on linux based OS's. My preferred browser is firefox however and I was hoping that this extension could be used to intercept links clicked in the chromium/teams app and open them in firefox. 

Is that out of scope for this extension? Is it not possible to implement in the way I describe?

**Comment by blipk** [comment]
Hi @alanmcg 

This isn't possible with bowser as it uses xdg-open which is only from links that are not in browsers.

A quick search shows this result that may be helpful although the extension seems outdated and not sure it's possible with newer versions of chromium: https://superuser.com/questions/663685/is-it-possible-to-open-links-in-chromium-in-other-browser
