### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by kimo-supremo** [blipk/bowser-gnome#19]
(bowser-gnome@kronosoul.xyz) [6/12/2023, 4:42:59 PM]::Info    | () => | enable()
(bowser-gnome@kronosoul.xyz) [6/12/2023, 4:43:08 PM]::Info    | () => | /var/lib/flatpak/exports/share/applications/one.ablaze.floorp.desktop
(bowser-gnome@kronosoul.xyz) [6/12/2023, 4:43:08 PM]::Info    | User Feedback | Bowser has detected changes in your installed web browsers.
(bowser-gnome@kronosoul.xyz) [6/12/2023, 4:43:08 PM]::Info    | enable() | ;
(bowser-gnome@kronosoul.xyz) [6/12/2023, 4:43:18 PM]::Info    | () => | disable()
(bowser-gnome@kronosoul.xyz) [6/12/2023, 4:43:18 PM]::Info    | disable() | ;
(bowser-gnome@kronosoul.xyz) [6/12/2023, 4:43:18 PM]::Info    | () => | enable()
(bowser-gnome@kronosoul.xyz) [6/12/2023, 4:43:18 PM]::Info    | enable() | ;
(bowser-gnome@kronosoul.xyz) [6/12/2023, 4:43:42 PM]::Info    | () => | /var/lib/flatpak/exports/share/applications/one.ablaze.floorp.desktop
(bowser-gnome@kronosoul.xyz) [6/12/2023, 4:43:42 PM]::Info    | User Feedback | No web browser changes detected.
(bowser-gnome@kronosoul.xyz) [6/12/2023, 4:43:47 PM]::Info    | User Feedback | Vivaldi (snapshot) is now your default browser.
(bowser-gnome@kronosoul.xyz) [6/12/2023, 4:45:29 PM]::Info    | User Feedback | New rule created.
(bowser-gnome@kronosoul.xyz) [6/12/2023, 4:46:08 PM]::Info    | User Feedback | youtube.com will now open with Vivaldi (snapshot)
(bowser-gnome@kronosoul.xyz) [6/12/2023, 4:46:48 PM]::Info    | User Feedback | Changes saved.
(bowser-gnome@kronosoul.xyz) [6/12/2023, 4:47:30 PM]::Info    | () => | disable()
(bowser-gnome@kronosoul.xyz) [6/12/2023, 4:47:30 PM]::Info    | disable() | ;
(bowser-gnome@kronosoul.xyz) [6/12/2023, 5:59:30 PM]::Info    | () => | enable()
(bowser-gnome@kronosoul.xyz) [6/12/2023, 5:59:39 PM]::Info    | enable() | ;
(bowser-gnome@kronosoul.xyz) [6/12/2023, 6:00:07 PM]::Info    | User Feedback | New rule created.
(bowser-gnome@kronosoul.xyz) [6/12/2023, 6:00:17 PM]::Info    | User Feedback | Vivaldi (snapshot) is now your default browser.
(bowser-gnome@kronosoul.xyz) [6/12/2023, 6:05:56 PM]::Info    | () => | disable()
(bowser-gnome@kronosoul.xyz) [6/12/2023, 6:05:56 PM]::Info    | disable() | ;
(bowser-gnome@kronosoul.xyz) [6/12/2023, 6:06:24 PM]::Info    | () => | enable()
(bowser-gnome@kronosoul.xyz) [6/12/2023, 6:06:33 PM]::Info    | enable() | ;
(bowser-gnome@kronosoul.xyz) [6/12/2023, 6:07:24 PM]::Info    | () => | disable()
(bowser-gnome@kronosoul.xyz) [6/12/2023, 6:07:24 PM]::Info    | disable() | ;
(bowser-gnome@kronosoul.xyz) [6/12/2023, 8:11:35 PM]::Info    | () => | enable()
(bowser-gnome@kronosoul.xyz) [6/12/2023, 8:11:44 PM]::Info    | enable() | ;
(bowser-gnome@kronosoul.xyz) [6/12/2023, 8:11:53 PM]::Info    | User Feedback | Vivaldi (snapshot) is now your default browser.
(bowser-gnome@kronosoul.xyz) [6/12/2023, 8:12:10 PM]::Info    | () => | /usr/share/applications/vivaldi-snapshot.desktop
(bowser-gnome@kronosoul.xyz) [6/12/2023, 8:12:10 PM]::Info    | User Feedback | No web browser changes detected.
(bowser-gnome@kronosoul.xyz) [6/12/2023, 8:12:29 PM]::Info    | () => | disable()
(bowser-gnome@kronosoul.xyz) [6/12/2023, 8:12:29 PM]::Info    | disable() | ;

**Describe the bug**
i removed the extension but there is an app that is still there

**To Reproduce**
Install extension
use exension
remove extension
check apps

**Expected behavior**
the app shouldn't be there

**Screenshots**
![image](https://github.com/blipk/bowser-gnome/assets/70135155/a6f8e75c-cda1-463a-bf17-ef1327b4478f)

**Desktop (please complete the following information):**
 - Gnome-Shell Version:  Debian 12 gnome 43
 - Browser: vivaldi
 - Extension Version [e.g. 22]

**Comment by blipk** [comment]
Gnome-shell provides no way to know when an extension is uninstalled so it's not possible to remove this automatically.

You can just delete the `bowser-gnome.desktop` file from `~/.local/share/applications` to remove the application launcher.
