### ISSUE TITLE
Installed but not working

### ISSUE THREAD

**Issue by joselsegura** [blipk/bowser-gnome#7]
Hi!

I find your extension on extensions.gnome.org and I found it really useful, I was looking for something like this before.
I installed it and enable both checkbox (Bowser and Create rules on new links), but when I click on a link, for example, in Thunderbird, nothing happens. And when I say nothing, is nothing: the default behavior (opening Firefox in my case) didn't work.
Probably it is a failure on my side... but I need some help to get it working.

I'm running Gnome Shell 3.36.2 from Debian Unstable repositories. Let me know if you need more info.

Thank you in advance

**Comment by blipk** [comment]
Hey,

Could you please upload the ~/.config/bowser-gnome@kronosoul.xyz/debug.log file

Thanks.

**Comment by joselsegura** [comment]
Hi!
I removed the extension and the `~/.config/bowser-gnome@kronosoul.xyz` directory in order to perform a "clean installation".

Steps:

1. Installed Bowser from Extensions webpage
2. Enable Bowser in the top bar icon

Resulting log: https://pastebin.com/hxnmuY8Z

I checked that the default browser has become "bowser" and if I click in any URL link, nothing happens apparently

**Comment by blipk** [comment]
Hmm that's strange, seems one of your apps doesn't have an exec string.

I have pushed an update here to github, you can extract the ZIP over your current installation, that should fix it.

If you are still having the issue let me know.

**Comment by joselsegura** [comment]
Hi @blipk,

First, thank you for your attention to this issue. I tried in a different OS (Fedora 31) and it works there.

I removed the current Bowser installation and the logs and configs from `~/.config/bowser-gnome@kronosoul.xyz`. Then, I cloned the repository in my `/tmp` and executed the `./install.sh` script. I ended with the extension installed, but the same problem.
I uploaded the `debug.log` again, hope it helps.

https://pastebin.com/79r9ggAj

**Comment by blipk** [comment]
Hmm, there was no MimeType string either in the desktop files. I uploaded another update that should fix it.

What web browsers do you have installed?
To prevent any further bugs could I get you to upload their .desktop files from /usr/share/applications or ~/.local/share/applications

**Comment by joselsegura** [comment]
I'm using current versions of Firefox, Firefox ESR, Chromium, Chrome and one .desktop file I created for a different Firefox profile.

This is weird, because I'm taking a look inside `/usr/share/applications/firefox.desktop` and I can see `MimeType`:

`$ ack MimeType /usr/share/applications/firefox.desktop 
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/vnd.mozilla.xul+xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;`

**Comment by blipk** [comment]
It may be one of the other browsers, I've updated a fix which will just default to a blank string, let me know how that goes. otherwise add `dev.log(id, app);` after line 346 in extension.js to see which desktop file the issue is with.

**Comment by joselsegura** [comment]
Hi!
The latest version you pushed to the repository is working now on Debian unstable too :-D
So I guess this issue can be closed, if you want.

As this problem happened only to me, apparently, I can provide more information if you want to find which `desktop` file is messing around with your extension.

Thank you a lot for your help and for the extension!

**Comment by joselsegura** [comment]
Well, wait a minute :-D

As I properly said, it **apparently** works.

Right now I can configure new rules, I see my browsers detected... but when I click on a link, for example, in Thunderbird, the link is not handled or it is not opened by any browser.

I checked the xdg-settings and the default-browser is `bowser-gnome.desktop`...

**Comment by joselsegura** [comment]
Quick update: the problem should be related to Thunderbird, not to Bowser. 

When opining links from different applications, it works fine, so the problem should be in the Thunderbird side.

**Comment by joselsegura** [comment]
I just found the problem using Thunderbird: when running from the terminal I saw a message like this `sh 1 cannot run ...../bowser.js. Permission denied` (sorry, I didn't copy it).
After a few research, I found that the generated `desktop` entry for Bowser contains, as `Exec`, a call to the `bowser.js`, which contains a shebangs in the first line.
Apparently Thunderbird tried to launch it as an sh script or it doesn't honor the shebangs... but changing the `Exec` line to running `gjs` and the extension script made the trick.
If I have some spare time this afternoon I will try to send a PR. Feel free to ignore or close it if it doesn't fit, I'm not a JS expert at all :-D

Best regards

**Comment by blipk** [comment]
Ah, interesting. Is Thunderbird running through Flatpak or Snap?

I have pushed an update to the .desktop file anyway which should solve this, if you could test that.

**Comment by joselsegura** [comment]
Hi!
I can confirm it works.
TYVM

**Comment by joselsegura** [comment]
And about your question, Thunderbird installed from Debian repositories, no Flatpak or Snap.

I run Telegram from Flatpak and Bowser works fine with it, even with the previous version
